### ISSUE TITLE
travis-ci updates upon release of node.js 12

### ISSUE THREAD

**Issue by coreyfarrell** [sindresorhus/meta#10]
Do you have a method for performing mass update of `.travis.yml` in your node.js packages to include testing against node.js 12 when it is released?  If not do you want a bunch of PR's that do nothing else but add 12 to the testing?  Obviously my target would be packages that I directly/indirectly use so probably 50-100 packages, but I figure this should still be helpful?  If I did this I would use the commit message `Add Node.js 12 to testing`.  Any additional required changes would be clearly noted, for example if a test had to be fixed to work on node.js 12.

**Comment by sindresorhus** [comment]
> Do you have a method for performing mass update of .travis.yml in your node.js packages to include testing against node.js 12 when it is released?

I don't. I usually just update `.travis.yml` manually when I do other changes to a module. Would be super handy with a tool like this though.

> but I figure this should still be helpful?

Yup. If you bother, feel free.

> I would use the commit message Add Node.js 12 to testing.

👍 Probably smart to do a test PR to ensure we agree on everything.

**Comment by coreyfarrell** [comment]
Test PR at sindresorhus/make-dir#16.

**Comment by coreyfarrell** [comment]
Unless you have an objection my plan is to pump out a bunch of essentially identical PR's but to let travis-ci handle running the tests.

I can notify you here when all the PR's I'm posting for the day have all passed CI (I'll include a search URL to list all the PR's).  I assume you wouldn't merge anything that hasn't gotten the green checkmark from CI anyways?

**Comment by coreyfarrell** [comment]
I ended up scripting this part of the way so I did run tests against node.js 12 on my local Fedora machine (`npm it` only took about 20 seconds per repo).  For now I've submitted 42 PR's, in all of these repos `.travis.yml` had an initial md5sum of `ed92fb84135848f0303385f200c4f5ad`, so all commits beyond the first were created by `git am` using a single patch file.

The only failure I ran into was with `import-fresh`, this was due to devDependency `heapdump` failing to build/install.  I've reported this error at bnoordhuis/node-heapdump#127.

All PR's have passed travis-ci, the search URL for these PR's is:
https://github.com/pulls?utf8=%E2%9C%93&q=is%3Aopen+is%3Apr+author%3Acoreyfarrell+user%3Asindresorhus+%22Add+Node.js+12+to+testing%22

**Comment by sindresorhus** [comment]
Great. Thanks for doing this. 👍

**Comment by coreyfarrell** [comment]
Not a problem, I use enough of your modules.  Next round of PR's have been posted and have now passed on travis-ci.  All of these are for `.travis.yml` files which started with md5sum of `7bfb7403565508c90b9f4c7147afa897` (so all identical PR's).  Same search URL will show you the list.

The only module which failed local testing is reported at sindresorhus/resolve-from#13 (the module isn't broken, just an expanded error message).

**Comment by sindresorhus** [comment]
I'm gonna close this, but feel free to continue discussing here or submit more PRs.

**Comment by coreyfarrell** [comment]
That's fine, the remaining packages on my list cannot be changed in bulk.  One thing I noticed 13 of the modules in my list have engines.node `>=0.10.0`.  Half of these are already marked deprecated (unnecessary ponyfills).  `deep-strict-equal` is a good candidate to deprecate as it is node.js only and requires `core-assert` which you already deprecated.  Others could potentially be used in legacy browsers but the native functionality exists in node.js 4:
* array-find-index
* code-point-at
* number-is-nan
* object-assign
* trim-right

**Comment by sindresorhus** [comment]
> deep-strict-equal is a good candidate to deprecate as it is node.js only and requires core-assert which you already deprecated.

Ok. I'll deprecate this one.

> Others could potentially be used in legacy browsers but the native functionality exists in node.js 4:

I'm aware of these, but I don't want to unnecessarily bother people. I'll deprecate them eventually, but no rush.
