### ISSUE TITLE
Use pnpm as the package manager of choice

### ISSUE THREAD

**Issue by ExE-Boss** [sindresorhus/meta#11]
> [pnpm](https://pnpm.js.org) uses hard links and symlinks to save one version of a module only ever once on a disk. When using npm or Yarn for example, if you have 100 projects using the same version of lodash, you will have 100 copies of lodash on disk. With pnpm, lodash will be saved in a single place on the disk and a hard link will put it into the `node_modules` where it should be installed.
>
> As a result, you save gigabytes of space on your disk and you have a lot faster installations! If you'd like more details about the unique `node_modules` structure that pnpm creates and why it works fine with the Node.js ecosystem, read this small article: [Flat node_modules is not the only way](https://medium.com/pnpm/flat-node-modules-is-not-the-only-way-d2e40f7296a3).

## See also:
- https://www.kochan.io/nodejs/why-should-we-use-pnpm.html
- https://medium.com/pnpm/pnpms-strictness-helps-to-avoid-silly-bugs-9a15fb306308
- https://medium.com/pnpm/flat-node-modules-is-not-the-only-way-d2e40f7296a3

**Comment by sindresorhus** [comment]
I think `pnpm` is a good idea, I just don't want to deal with the ecosystem incompatibilities. npm works well enough for me.

**Comment by ExE-Boss** [comment]
Well, 99.9% of all npm packages work just fine with pnpm.

For the remaining 0.1%, there’s [`pnpmfile.js`](https://pnpm.js.org/docs/hooks.html) and [`@pnpm/hook‑utils`](https://github.com/pnpm/hook-utils) [![(on npm)](https://img.shields.io/npm/v/@pnpm/hook-utils.svg)](https://www.npmjs.com/package/@pnpm/hook-utils).

**Comment by fregante** [comment]
The fact that it has its own package lock and resolution means that every user of a project has to use it, or else they will have different versions. 

There are tools that delete old node_modules or hard-link existing ones. Actually I think hard linking directories isn’t currently supported in OS X so this won’t work that well

**Comment by zkochan** [comment]
I think the answer Sindre gave is satisfactory. As far as I know, he currently does not commit the `package-lock.json`, so other contributors may use yarn or pnpm if they prefer to (pnpm also respects the `package-lock` config).

> There are tools that delete old node_modules or hard-link existing ones. Actually I think hard linking directories isn’t currently supported in OS X so this won’t work that well

I think this repo is not a place to promote pnpm but pnpm exists for 4 years and many Mac users love it as it saves space on their devices that have small SSD. Hard links work with no issues on Windows/Linux/OSX
