### ISSUE TITLE
TypeScript definitions for my packages

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/meta#9]
@BendingBender is helping me adding TypeScript definitions to a lot of my packages: https://github.com/search?q=user%3Asindresorhus+author%3ABendingBender+is%3Apr+typescript 🙌

We can use this space to discuss high-level things.

**Comment by sindresorhus** [comment]
@BendingBender Would you be able to prioritize https://github.com/sindresorhus/electron-better-ipc ? I've gotten a couple of emails about doing TypeScript definitions for it.

**Comment by BendingBender** [comment]
Will do next.

**Comment by BendingBender** [comment]
Note to myself: clarify usage of `Array`/`ReadonlyArray` in https://github.com/sindresorhus/typescript-definition-style-guide

**Comment by sindresorhus** [comment]
@BendingBender When a function returns an array, should we make it `readonly`?

```ts
foo(bar: string): readonly string[];
```

Or is it pointless?

**Comment by BendingBender** [comment]
I wouldn't do it. I would usually expect a library to give me something I can use for every purpose, not something unnecessary limited. Otherwise I would have to cast/copy the array, this is not very nice ergonomics-wise.

**Comment by sindresorhus** [comment]
@BendingBender That's a very good point. So `readonly` for all input, but never `readonly` for return values. Correct? If so, I'll update the style guide.

**Comment by sindresorhus** [comment]
@BendingBender Would you be able to prioritize https://github.com/sindresorhus/linkify-urls and https://github.com/sindresorhus/linkify-issues? We need it for Refined GitHub.

Context: https://github.com/sindresorhus/refined-github/pull/1783/files#diff-98a7886093e2e560968c34d6c4707b22R11

**Comment by sindresorhus** [comment]
@BendingBender Node.js 12 is out, so would be great if you could add it to `.travis.yml` when you do PRs. Like: https://github.com/sindresorhus/got/commit/bf1aa5492ae2bc78cbbec6b7d764906fb156e6c2#diff-354f30a63fb0907d4ad57269548329e3R3

**Comment by BendingBender** [comment]
Will do.

**Comment by sindresorhus** [comment]
@BendingBender I know you didn't do this type definition, but would you be able to help convert it to CommonJS-style? https://github.com/chalk/chalk/blob/master/index.d.ts (It can be a breaking change as we're planning a major release there)

**Comment by fregante** [comment]
Like https://github.com/sindresorhus/mem/pull/32 ?

**Comment by sindresorhus** [comment]
@bfred-it Yup

**Comment by BendingBender** [comment]
> I know you didn't do this type definition, but would you be able to help convert it to CommonJS-style? chalk/chalk:index.d.ts@master (It can be a breaking change as we're planning a major release there)

Done.

**Comment by sindresorhus** [comment]
@BendingBender I couldn't find your email. Could you email me at sindresorhus@gmail.com ? I have something to discuss.

**Comment by BendingBender** [comment]
@sindresorhus I've sent you an email.

**Comment by sindresorhus** [comment]
@BendingBender Is there any way to get VS Code and other editors to show the resolved properties? I have this https://github.com/sindresorhus/crypto-random-string/blob/32365366245e602a58a2a38c4d6fc2edd30355d7/index.d.ts#L52 and it shows up as something completely unreadable:

<img width="814" alt="Screen Shot 2019-05-08 at 17 51 07" src="https://user-images.githubusercontent.com/170270/57439441-3bff4700-7270-11e9-84f2-08996d8261a9.png">

Alternatively, a better way to write the definition.

**Comment by BendingBender** [comment]
As far as I can see it, there is no better way to type this without giving up the exclusivity of `type`/`characters` options.

I think that this definition would be clearer:
```ts
interface BaseOptions {...}
interface TypeOptions extends BaseOptions {...}
interface CharactersOptions extends BaseOptions {...}

type Options = MergeExclusive<TypeOptions, CharactersOptions>;
```
But it is still rendered quite ugly in the suggestion tooltip.

The only other way I can think of is to use discriminated union types, but I have no idea how to do this here without hurting ergonomics:
```ts
interface BaseOptions {...}
interface TypeOptions extends BaseOptions {
	kind: 'types';
	type?: 'hex' | 'base64' | 'url-safe';
}
interface CharactersOptions extends BaseOptions {
	kind: 'characters';
	characters?: string;
}

type Options = TypeOptions | CharactersOptions; // <- this one always needs the 'kind' property :-(
```

**Comment by ExE-Boss** [comment]
You could do:
```ts
interface BaseOptions { … }
interface TypeOptions extends BaseOptions {
	kind: 'types';
	type?: 'hex' | 'base64' | 'url-safe';
}
interface CharactersOptions extends BaseOptions {
	kind: 'characters';
	characters?: string;
}

// No longer needs the `kind` property:
type Options = BaseOptions | TypeOptions | CharactersOptions;
```

**Comment by BendingBender** [comment]
@ExE-Boss Sorry but I've tried this before, this basically renders the type a non-discriminated union type. Thus all properties simply become optional and non-exclusive.

**Comment by sindresorhus** [comment]
Hmm, too bad. Really wish TypeScript and VS Code had a better way to handle this.

**Comment by sindresorhus** [comment]
@BendingBender Would you be able to prioritize https://github.com/sindresorhus/mimic-response ?

**Comment by ExE-Boss** [comment]
I’m in the process of writing the type definitions for `mimic-response`.
